stages:
  collect:
    cmd: python src/data_load.py
    deps:
      - src/data_load.py
      - params.yaml
    outs:
      - data/raw/day.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/day.csv
      - params.yaml
    outs:
      - data/processed/preprocessed.csv

  features:
    cmd: python src/features.py
    deps:
      - src/features.py
      - data/processed/preprocessed.csv
      - params.yaml
    outs:
      - data/features/train.csv
      - data/features/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/features/train.csv
      - params.yaml
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/features/test.csv
      - params.yaml
    outs:
      - metrics/metrics.json
